version: "3.2"
services:
    db:
        image: postgres
        environment:
            - POSTGRES_DB=commerce
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
        ports:
            - "5432:5432"
        restart: always
        networks:
            - commerce_net
    messaging:
        image: rabbitmq:3-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - commerce_net
networks:
    commerce_net:
        driver: bridge